from typing import List, Optional
from fastapi import FastAPI, Depends, HTTPException, status, File, UploadFile, Form, Query
from starlette.concurrency import run_in_threadpool
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from sqlalchemy.orm import Session, joinedload
from sqlalchemy.exc import IntegrityError
import models
import schemas
from database import engine, get_db
import os
import shutil
import uuid
import base64
import numpy as np
import cv2
from body_measure_engine import BodyMeasureEngine

_measure_engine: BodyMeasureEngine = None

def get_measure_engine() -> BodyMeasureEngine:
    global _measure_engine
    if _measure_engine is None:
        _measure_engine = BodyMeasureEngine()
    return _measure_engine

# DB 테이블 자동 생성
try:
    if engine:
        models.Base.metadata.create_all(bind=engine)
except Exception as e:
    print(f"DB Table creation error: {e}")

app = FastAPI(title="Capstone Design FastAPI", version="1.0.0")

# 서버 시작 시 초기 카테고리(상의, 바지) 생성
@app.on_event("startup")
def startup():
    get_measure_engine()
    try:
        auto_migrate_db()
    except Exception as e:
        print(f"DB migration skipped (DB unavailable): {e}")
    try:
        seed_data()
    except Exception as e:
        print(f"Seed data skipped (DB unavailable): {e}")

def auto_migrate_db():
    from sqlalchemy import text
    from database import engine
    if engine is None:
        raise RuntimeError("DB engine not initialized")
    with engine.connect() as conn:
        # Drop legacy table
        try:
            conn.execute(text("DROP TABLE product_sizes"))
            conn.commit()
            print("Dropped old product_sizes table.")
        except Exception:
            pass

        # Add ALL potentially missing columns to products
        for col_ddl in [
            "ALTER TABLE products ADD brand VARCHAR2(100)",
            "ALTER TABLE products ADD description CLOB",
            "ALTER TABLE products ADD owner_email VARCHAR2(100)",
            "ALTER TABLE products ADD avg_rating NUMBER(5,2) DEFAULT 0",
            "ALTER TABLE products ADD review_count INTEGER DEFAULT 0",
            "ALTER TABLE products ADD wish_count INTEGER DEFAULT 0",
            "ALTER TABLE products ADD fitting_image_url VARCHAR2(500)",
        ]:
            try:
                conn.execute(text(col_ddl))
                conn.commit()
                print(f"Migration OK: {col_ddl[:70]}")
            except Exception:
                pass  # column already exists — safe to ignore

        # Create avatars table
        try:
            conn.execute(text("""
                CREATE TABLE avatars (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_email VARCHAR2(100) NOT NULL UNIQUE,
                    gray_mask_url VARCHAR2(500),
                    person_extracted_url VARCHAR2(500),
                    measurements CLOB,
                    height_cm NUMBER(6,2),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP
                )
            """))
            conn.commit()
            print("Created avatars table.")
        except Exception as e:
            e_str = str(e)
            if "ORA-00955" not in e_str and "already exists" not in e_str.lower():
                print(f"avatars table note: {e_str[:120]}")

        # Create cart_items table
        try:
            conn.execute(text("""
                CREATE TABLE cart_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_email VARCHAR2(100) NOT NULL,
                    product_id INTEGER NOT NULL,
                    size_name VARCHAR2(50),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """))
            conn.commit()
            print("Created cart_items table.")
        except Exception as e:
            e_str = str(e)
            if "ORA-00955" not in e_str and "already exists" not in e_str.lower():
                print(f"cart_items table note: {e_str[:120]}")

        print("DB auto-migration completed.")

def seed_data():
    from database import SessionLocal
    db = SessionLocal()
    try:
        categories = ["상의 (Top)", "바지 (Pants)"]
        for cat_name in categories:
            exists = db.query(models.Category).filter(models.Category.name == cat_name).first()
            if not exists:
                new_cat = models.Category(name=cat_name)
                db.add(new_cat)
        db.commit()
    except Exception as e:
        print(f"Seeding error: {e}")
    finally:
        db.close()

# 이미지 업로드 설정 및 정적 파일 서빙
UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)
SIZE_REVIEW_DIR = os.path.join(UPLOAD_DIR, "size_review_image")
os.makedirs(SIZE_REVIEW_DIR, exist_ok=True)
AVATAR_DIR = os.path.join(UPLOAD_DIR, "avatars")
os.makedirs(AVATAR_DIR, exist_ok=True)
FITTING_DIR = os.path.join(UPLOAD_DIR, "fitting_images")
os.makedirs(FITTING_DIR, exist_ok=True)
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")

# CORS 설정: React 프론트엔드 도메인 허용
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:5174", "http://localhost:3000", "http://127.0.0.1:5173", "http://127.0.0.1:5174", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Welcome to Backend API"}

# --- 사용자 인증 ---

@app.post("/api/register", response_model=schemas.UserResponse)
def register_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # MVP 수준의 구현으로 패스워드 평문 저장 (운영 시 passlib 등으로 해싱 필수)
    new_user = models.User(username=user.username, email=user.email, password=user.password)
    try:
        db.add(new_user)
        db.commit()
        db.refresh(new_user)
        return new_user
    except IntegrityError:
        db.rollback()
        raise HTTPException(status_code=400, detail="Username or Email already registered")
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail="Database error")

@app.post("/api/login")
def login_user(user: schemas.UserLogin, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.email == user.email).first()
    if not db_user or db_user.password != user.password:
        raise HTTPException(status_code=401, detail="Invalid email or password")
    return {"username": db_user.username, "email": db_user.email, "access_token": "fake-jwt-token"}

# --- 신체 측정 엔진 관리 ---
_measure_engine = None

def get_measure_engine():
    global _measure_engine
    if _measure_engine is None:
        _measure_engine = BodyMeasureEngine()
    return _measure_engine

# --- 신체 측정 엔드포인트 ---
@app.post("/api/measure")
async def measure_body(
    image: UploadFile = File(...),
    height_cm: float = Form(...),
):
    contents = await image.read()
    nparr = np.frombuffer(contents, np.uint8)
    image_bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    if image_bgr is None:
        raise HTTPException(status_code=400, detail="이미지를 읽을 수 없습니다.")

    try:
        engine = get_measure_engine()
        # rembg(u2net) CPU 추론이 동기 블로킹이므로 스레드풀에서 실행
        result = await run_in_threadpool(engine.analyze, image_bgr, height_cm)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"분석 중 오류 발생: {str(e)}")

    def _encode(img):
        _, buf = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, 85])
        return base64.b64encode(buf).decode("utf-8")

    return {
        "pose_valid":              result["pose_valid"],
        "warnings":                result["warnings"],
        "measurements":            result["measurements"],
        "cm_per_pixel":            result["cm_per_pixel"],
        "debug_image_base64":      _encode(result["debug_image"]),
        "person_extracted_base64": _encode(result["person_extracted"]),
        "gray_mask_base64":        _encode(result["gray_mask"]),
        "gray_debug_image_base64": _encode(result["gray_debug_image"]),
    }

# --- 의류 치수 측정 엔드포인트 ---
from clothing_measure_engine import ClothingMeasureEngine

_clothing_measure_engine = None

def get_clothing_measure_engine():
    global _clothing_measure_engine
    if _clothing_measure_engine is None:
        _clothing_measure_engine = ClothingMeasureEngine()
    return _clothing_measure_engine

@app.post("/api/measure/clothing")
async def measure_clothing(
    shirt_image: UploadFile = File(...),
    a4_image: UploadFile = File(...),
    shirt_x: float = Form(...),
    shirt_y: float = Form(...),
    shirt_w: float = Form(...),
    shirt_h: float = Form(...),
    a4_x: float = Form(...),
    a4_y: float = Form(...),
    a4_w: float = Form(...),
    a4_h: float = Form(...),
    orig_w: float = Form(...),
    orig_h: float = Form(...),
    category_type: str = Form('Top'),
    shoulder_x1: float = Form(None),
    shoulder_y1: float = Form(None),
    shoulder_x2: float = Form(None),
    shoulder_y2: float = Form(None),
):
    shirt_bytes = await shirt_image.read()
    a4_bytes = await a4_image.read()

    shirt_rect = {'x': shirt_x, 'y': shirt_y, 'w': shirt_w, 'h': shirt_h}
    a4_rect = {'x': a4_x, 'y': a4_y, 'w': a4_w, 'h': a4_h}

    try:
        engine = get_clothing_measure_engine()
        
        shoulder_pts = None
        if shoulder_x1 is not None and shoulder_y1 is not None and shoulder_x2 is not None and shoulder_y2 is not None:
            shoulder_pts = [(shoulder_x1, shoulder_y1), (shoulder_x2, shoulder_y2)]

        result = await run_in_threadpool(
            engine.process, 
            shirt_bytes, a4_bytes, 
            shirt_rect, a4_rect, 
            orig_w, orig_h,
            category_type,
            shoulder_pts
        )
        return result
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"분석 중 오류 발생: {str(e)}")


# --- 상품 및 통계 관리 ---

def to_float(val):
    if val is None or (isinstance(val, str) and val.strip() == ''):
        return None
    try:
        return float(val)
    except (ValueError, TypeError):
        return None

# 리뷰/찜 변경 시 상품의 평균 별점과 카운트 동기화
def update_product_stats(product_id: int, db: Session):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if product:
        reviews = product.reviews
        if reviews:
            product.avg_rating = round(sum(r.rating for r in reviews) / len(reviews), 1)
            product.review_count = len(reviews)
        else:
            product.avg_rating = 0.0
            product.review_count = 0
        product.wish_count = db.query(models.Wish).filter(models.Wish.product_id == product_id).count()
        db.commit()

@app.get("/api/products", response_model=list[schemas.ProductResponse])
def get_products(user_email: str = None, db: Session = Depends(get_db)):
    products = db.query(models.Product).order_by(models.Product.id.desc()).all()
    results = []
    for p in products:
        item = schemas.ProductResponse.from_orm(p)
        if user_email:
            item.is_wished = db.query(models.Wish).filter(models.Wish.product_id == p.id, models.Wish.user_email == user_email).first() is not None
        results.append(item)
    return results

@app.get("/api/products/{product_id}", response_model=schemas.ProductResponse)
def get_product_detail(product_id: int, user_email: str = None, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")
    item = schemas.ProductResponse.from_orm(product)
    if user_email:
        item.is_wished = db.query(models.Wish).filter(models.Wish.product_id == product.id, models.Wish.user_email == user_email).first() is not None
    return item

import json

@app.post("/api/products", response_model=schemas.ProductResponse)
def create_product(
    category_id: int = Form(...), name: str = Form(...), brand: str = Form(...), price: int = Form(...),
    description: Optional[str] = Form(None), sizes: Optional[str] = Form(None), image: UploadFile = File(...), desc_images: List[UploadFile] = File([]),
    owner_email: str = Form(...), db: Session = Depends(get_db)
):
    try:
        # 메인 이미지 저장
        file_ext = image.filename.split(".")[-1]
        unique_filename = f"{uuid.uuid4().hex}.{file_ext}"
        image_path = os.path.join(UPLOAD_DIR, unique_filename)
        with open(image_path, "wb") as buffer:
            shutil.copyfileobj(image.file, buffer)
        image_url = f"/{UPLOAD_DIR}/{unique_filename}"
        
        new_product = models.Product(
            category_id=category_id, name=name, brand=brand, price=price, description=description,
            image_url=image_url, owner_email=owner_email
        )
        db.add(new_product)
        # Flush to get ID without committing yet
        db.flush()

        # 사이즈 다중 저장
        if sizes:
            sizes_data = json.loads(sizes)
            cat = db.query(models.Category).filter(models.Category.id == category_id).first()
            is_top = cat and "상의" in cat.name

            for s in sizes_data:
                if is_top:
                    new_size = models.TopSize(
                        product_id=new_product.id,
                        size_name=s.get("size_name"),
                        length=to_float(s.get("length")),
                        chest=to_float(s.get("chest")),
                        shoulder=to_float(s.get("shoulder")),
                        sleeve=to_float(s.get("sleeve")),
                        neck=to_float(s.get("neck"))
                    )
                else:
                    new_size = models.BottomSize(
                        product_id=new_product.id,
                        size_name=s.get("size_name"),
                        length=to_float(s.get("length")),
                        waist=to_float(s.get("waist")),
                        thigh=to_float(s.get("thigh")),
                        rise=to_float(s.get("rise")),
                        hem=to_float(s.get("hem"))
                    )
                db.add(new_size)

        # 상세 이미지 다중 저장
        if desc_images:
            for d_img in desc_images:
                if d_img and d_img.filename:
                    d_img.file.seek(0)
                    d_file_ext = d_img.filename.split(".")[-1]
                    d_unique_filename = f"{uuid.uuid4().hex}.{d_file_ext}"
                    d_image_path = os.path.join(UPLOAD_DIR, d_unique_filename)
                    with open(d_image_path, "wb") as buffer:
                        shutil.copyfileobj(d_img.file, buffer)
                    new_img = models.ProductImage(product_id=new_product.id, image_url=f"/{UPLOAD_DIR}/{d_unique_filename}")
                    db.add(new_img)
        
        db.commit()
        db.refresh(new_product)
        return new_product
    except Exception as e:
        db.rollback()
        print(f"ERROR creating product: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to create product: {str(e)}")

@app.put("/api/products/{product_id}", response_model=schemas.ProductResponse)
def update_product(
    product_id: int, category_id: int = Form(...), name: str = Form(...), brand: str = Form(...), price: int = Form(...),
    description: Optional[str] = Form(None), sizes: Optional[str] = Form(None), image: UploadFile = File(None), desc_images: List[UploadFile] = File([]),
    owner_email: str = Form(...), db: Session = Depends(get_db)
):
    db_product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not db_product or db_product.owner_email != owner_email:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    db_product.category_id = category_id
    db_product.name = name
    db_product.brand = brand
    db_product.price = price
    db_product.description = description
    
    if sizes:
        # 기존 사이즈 삭제
        db.query(models.TopSize).filter(models.TopSize.product_id == product_id).delete()
        db.query(models.BottomSize).filter(models.BottomSize.product_id == product_id).delete()
        
        sizes_data = json.loads(sizes)
        cat = db.query(models.Category).filter(models.Category.id == category_id).first()
        is_top = cat and "상의" in cat.name

        for s in sizes_data:
            if is_top:
                new_size = models.TopSize(
                    product_id=db_product.id,
                    size_name=s.get("size_name"),
                    length=to_float(s.get("length")),
                    chest=to_float(s.get("chest")),
                    shoulder=to_float(s.get("shoulder")),
                    sleeve=to_float(s.get("sleeve")),
                    neck=to_float(s.get("neck"))
                )
            else:
                new_size = models.BottomSize(
                    product_id=db_product.id,
                    size_name=s.get("size_name"),
                    length=to_float(s.get("length")),
                    waist=to_float(s.get("waist")),
                    thigh=to_float(s.get("thigh")),
                    rise=to_float(s.get("rise")),
                    hem=to_float(s.get("hem"))
                )
            db.add(new_size)
    
    if image and image.filename:
        file_ext = image.filename.split(".")[-1]
        unique_filename = f"{uuid.uuid4().hex}.{file_ext}"
        with open(os.path.join(UPLOAD_DIR, unique_filename), "wb") as buffer:
            shutil.copyfileobj(image.file, buffer)
        db_product.image_url = f"/{UPLOAD_DIR}/{unique_filename}"
        
    if desc_images:
        db.query(models.ProductImage).filter(models.ProductImage.product_id == product_id).delete()
        for d_img in desc_images:
            if d_img and d_img.filename:
                d_img.file.seek(0)
                d_file_ext = d_img.filename.split(".")[-1]
                d_unique_filename = f"{uuid.uuid4().hex}.{d_file_ext}"
                with open(os.path.join(UPLOAD_DIR, d_unique_filename), "wb") as buffer:
                    shutil.copyfileobj(d_img.file, buffer)
                new_img = models.ProductImage(product_id=product_id, image_url=f"/{UPLOAD_DIR}/{d_unique_filename}")
                db.add(new_img)
        
    db.commit()
    db.refresh(db_product)
    return db_product

@app.delete("/api/products/{product_id}")
def delete_product(product_id: int, owner_email: str, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product or product.owner_email != owner_email:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    db.delete(product)
    db.commit()
    return {"message": "Deleted"}

# --- 찜(Wish) ---

@app.post("/api/wishes/toggle")
def toggle_wish(product_id: int = Form(...), user_email: str = Form(...), db: Session = Depends(get_db)):
    existing = db.query(models.Wish).filter(models.Wish.product_id == product_id, models.Wish.user_email == user_email).first()
    if existing:
        db.delete(existing)
        db.commit()
        update_product_stats(product_id, db)
        return {"status": "removed"}
    else:
        db.add(models.Wish(product_id=product_id, user_email=user_email))
        db.commit()
        update_product_stats(product_id, db)
        return {"status": "added"}

@app.get("/api/wishes/{user_email}", response_model=list[schemas.WishResponse])
def get_user_wishes(user_email: str, db: Session = Depends(get_db)):
    wishes = db.query(models.Wish).filter(models.Wish.user_email == user_email).all()
    results = []
    for w in wishes:
        p_item = schemas.ProductResponse.from_orm(w.product)
        p_item.is_wished = True
        results.append({"id": w.id, "user_email": w.user_email, "product_id": w.product_id, "product": p_item})
    return results

# --- 리뷰(Review) ---

@app.post("/api/reviews", response_model=schemas.ReviewResponse)
def create_review(
    product_id: int = Form(...), user_email: str = Form(...), rating: int = Form(...),
    comment: str = Form(...), images: List[UploadFile] = File([]), db: Session = Depends(get_db)
):
    try:
        new_review = models.Review(product_id=product_id, user_email=user_email, rating=rating, comment=comment)
        db.add(new_review)
        db.flush()

        if images:
            for img in images:
                if img and img.filename:
                    img.file.seek(0)
                    file_ext = img.filename.split(".")[-1]
                    unique_filename = f"review_{uuid.uuid4().hex}.{file_ext}"
                    with open(os.path.join(UPLOAD_DIR, unique_filename), "wb") as buffer:
                        shutil.copyfileobj(img.file, buffer)
                    
                    new_img = models.ReviewImage(review_id=new_review.id, image_url=f"/{UPLOAD_DIR}/{unique_filename}")
                    db.add(new_img)
                    
                    # 호환성을 위해 첫 번째 이미지를 메인 image_url에 저장
                    if not new_review.image_url:
                        new_review.image_url = f"/{UPLOAD_DIR}/{unique_filename}"

        db.commit()
        db.refresh(new_review)
        update_product_stats(product_id, db)
        return new_review
    except Exception as e:
        db.rollback()
        print(f"Error creating review: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/reviews/{review_id}", response_model=schemas.ReviewResponse)
def get_review_detail(review_id: int, db: Session = Depends(get_db)):
    review = db.query(models.Review).filter(models.Review.id == review_id).first()
    if not review:
        raise HTTPException(status_code=404, detail="Review not found")
    return review

@app.put("/api/reviews/{review_id}", response_model=schemas.ReviewResponse)
def update_review(
    review_id: int, rating: int = Form(...), comment: str = Form(...),
    images: List[UploadFile] = File([]), user_email: str = Form(...), db: Session = Depends(get_db)
):
    db_review = db.query(models.Review).filter(models.Review.id == review_id).first()
    if not db_review or db_review.user_email != user_email:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    db_review.rating = rating
    db_review.comment = comment

    if images:
        # 기존 이미지 기록 삭제
        db.query(models.ReviewImage).filter(models.ReviewImage.review_id == review_id).delete()
        db_review.image_url = None # 초기화
        
        for img in images:
            if img and img.filename:
                img.file.seek(0)
                file_ext = img.filename.split(".")[-1]
                unique_filename = f"review_{uuid.uuid4().hex}.{file_ext}"
                with open(os.path.join(UPLOAD_DIR, unique_filename), "wb") as buffer:
                    shutil.copyfileobj(img.file, buffer)
                
                new_img = models.ReviewImage(review_id=review_id, image_url=f"/{UPLOAD_DIR}/{unique_filename}")
                db.add(new_img)
                
                if not db_review.image_url:
                    db_review.image_url = f"/{UPLOAD_DIR}/{unique_filename}"
        
    db.commit()
    db.refresh(db_review)
    update_product_stats(db_review.product_id, db)
    return db_review

@app.delete("/api/reviews/{review_id}")
def delete_review(review_id: int, user_email: str, db: Session = Depends(get_db)):
    review = db.query(models.Review).filter(models.Review.id == review_id).first()
    if not review or review.user_email != user_email:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    product_id = review.product_id
    db.delete(review)
    db.commit()
    update_product_stats(product_id, db)
    return {"message": "Deleted"}

@app.get("/api/reviews/user/{email}", response_model=list[schemas.ReviewResponse])
def get_user_reviews(email: str, db: Session = Depends(get_db)):
    return db.query(models.Review).options(joinedload(models.Review.images), joinedload(models.Review.product)).filter(models.Review.user_email == email).order_by(models.Review.created_at.desc()).all()

@app.get("/api/products/{product_id}/reviews", response_model=list[schemas.ReviewResponse])
def get_product_reviews(product_id: int, db: Session = Depends(get_db)):
    return db.query(models.Review).options(joinedload(models.Review.images), joinedload(models.Review.product)).filter(models.Review.product_id == product_id).order_by(models.Review.created_at.desc()).all()

@app.get("/api/categories", response_model=list[schemas.CategoryResponse])
def get_categories(db: Session = Depends(get_db)):
    return db.query(models.Category).all()

@app.get("/api/products/user/{email}", response_model=list[schemas.ProductResponse])
def get_user_products(email: str, db: Session = Depends(get_db)):
    return db.query(models.Product).filter(models.Product.owner_email == email).order_by(models.Product.id.desc()).all()

# --- 사이즈 후기 (Size Review) ---

@app.post("/api/size-reviews", response_model=schemas.SizeReviewResponse)
async def create_size_review(
    product_id: int = Form(...),
    user_email: str = Form(...),
    size_name: str = Form(...),
    length: Optional[float] = Form(None),
    chest_or_waist: Optional[float] = Form(None),
    shoulder_or_thigh: Optional[float] = Form(None),
    sleeve_or_rise: Optional[float] = Form(None),
    neck_or_hem: Optional[float] = Form(None),
    debug_image: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    try:
        existing_review = db.query(models.SizeReview).filter(
            models.SizeReview.product_id == product_id,
            models.SizeReview.user_email == user_email
        ).first()

        if existing_review:
            # 기존 리뷰 수정
            existing_review.size_name = size_name
            existing_review.length = length
            existing_review.chest_or_waist = chest_or_waist
            existing_review.shoulder_or_thigh = shoulder_or_thigh
            existing_review.sleeve_or_rise = sleeve_or_rise
            existing_review.neck_or_hem = neck_or_hem

            # 기존 이미지 파일 삭제
            for img in existing_review.images:
                file_path = os.path.join(SIZE_REVIEW_DIR, os.path.basename(img.image_url))
                if os.path.exists(file_path):
                    try: os.remove(file_path)
                    except: pass
                db.delete(img)
            
            new_review = existing_review
        else:
            # 새 리뷰 생성
            new_review = models.SizeReview(
                product_id=product_id,
                user_email=user_email,
                size_name=size_name,
                length=length,
                chest_or_waist=chest_or_waist,
                shoulder_or_thigh=shoulder_or_thigh,
                sleeve_or_rise=sleeve_or_rise,
                neck_or_hem=neck_or_hem
            )
            db.add(new_review)
        
        db.flush()

        # 디버그 이미지 저장 (최종 결과 이미지)
        file_ext = debug_image.filename.split(".")[-1]
        unique_filename = f"sr_{uuid.uuid4().hex}.{file_ext}"
        save_path = os.path.join(SIZE_REVIEW_DIR, unique_filename)
        
        with open(save_path, "wb") as buffer:
            shutil.copyfileobj(debug_image.file, buffer)
        
        image_url = f"/uploads/size_review_image/{unique_filename}"
        new_img = models.SizeReviewImage(size_review_id=new_review.id, image_url=image_url)
        db.add(new_img)
        
        db.commit()
        db.refresh(new_review)
        return new_review
    except Exception as e:
        db.rollback()
        print(f"Error creating size review: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/products/{product_id}/size-reviews", response_model=list[schemas.SizeReviewResponse])
def get_product_size_reviews(product_id: int, db: Session = Depends(get_db)):
    return db.query(models.SizeReview).options(joinedload(models.SizeReview.images)).filter(models.SizeReview.product_id == product_id).order_by(models.SizeReview.created_at.desc()).all()

@app.delete("/api/size-reviews/{review_id}")
def delete_size_review(review_id: int, user_email: str = Query(...), db: Session = Depends(get_db)):
    review = db.query(models.SizeReview).filter(models.SizeReview.id == review_id, models.SizeReview.user_email == user_email).first()
    if not review:
        raise HTTPException(status_code=404, detail="Review not found or unauthorized")

    for img in review.images:
        file_path = os.path.join(SIZE_REVIEW_DIR, os.path.basename(img.image_url))
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception as e:
                print(f"Failed to delete image {file_path}: {e}")

    db.delete(review)
    db.commit()
    return {"message": "Deleted successfully"}


# --- 아바타 (Avatar) ---

def _parse_avatar(avatar):
    import json as _json
    d = {
        "id": avatar.id,
        "user_email": avatar.user_email,
        "gray_mask_url": avatar.gray_mask_url,
        "person_extracted_url": avatar.person_extracted_url,
        "height_cm": avatar.height_cm,
        "measurements": None,
    }
    if avatar.measurements:
        try:
            d["measurements"] = _json.loads(avatar.measurements)
        except Exception:
            d["measurements"] = avatar.measurements
    return d

@app.post("/api/avatar/save", response_model=schemas.AvatarResponse)
async def save_avatar(
    user_email: str = Form(...),
    height_cm: float = Form(...),
    measurements: str = Form(...),
    gray_mask: UploadFile = File(...),
    person_extracted: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    import json as _json

    def _save_file(upload: UploadFile, prefix: str) -> str:
        ext = upload.filename.split(".")[-1] if upload.filename and "." in upload.filename else "jpg"
        fname = f"{prefix}_{uuid.uuid4().hex}.{ext}"
        path = os.path.join(AVATAR_DIR, fname)
        upload.file.seek(0)
        with open(path, "wb") as f:
            shutil.copyfileobj(upload.file, f)
        return f"/uploads/avatars/{fname}"

    gray_url = _save_file(gray_mask, "gray")
    extracted_url = _save_file(person_extracted, "extracted")

    # Store measurements as JSON string (Oracle CLOB / Text column)
    m_str = measurements  # already a JSON string from the client

    existing = db.query(models.Avatar).filter(models.Avatar.user_email == user_email).first()
    if existing:
        for old_url in [existing.gray_mask_url, existing.person_extracted_url]:
            if old_url:
                old_path = os.path.join(AVATAR_DIR, os.path.basename(old_url))
                if os.path.exists(old_path):
                    try:
                        os.remove(old_path)
                    except Exception:
                        pass
        existing.gray_mask_url = gray_url
        existing.person_extracted_url = extracted_url
        existing.measurements = m_str
        existing.height_cm = height_cm
        db.commit()
        db.refresh(existing)
        return _parse_avatar(existing)
    else:
        avatar = models.Avatar(
            user_email=user_email,
            gray_mask_url=gray_url,
            person_extracted_url=extracted_url,
            measurements=m_str,
            height_cm=height_cm
        )
        db.add(avatar)
        db.commit()
        db.refresh(avatar)
        return _parse_avatar(avatar)


@app.get("/api/avatar/{user_email}", response_model=schemas.AvatarResponse)
def get_avatar(user_email: str, db: Session = Depends(get_db)):
    avatar = db.query(models.Avatar).filter(models.Avatar.user_email == user_email).first()
    if not avatar:
        raise HTTPException(status_code=404, detail="Avatar not found")
    return _parse_avatar(avatar)


# --- 장바구니 (Cart) ---

@app.post("/api/cart/add", response_model=schemas.CartItemResponse)
def add_to_cart(
    user_email: str = Form(...),
    product_id: int = Form(...),
    size_name: str = Form(None),
    db: Session = Depends(get_db)
):
    existing = db.query(models.CartItem).filter(
        models.CartItem.user_email == user_email,
        models.CartItem.product_id == product_id,
        models.CartItem.size_name == size_name
    ).first()
    if existing:
        return existing
    item = models.CartItem(user_email=user_email, product_id=product_id, size_name=size_name)
    db.add(item)
    db.commit()
    db.refresh(item)
    return item


@app.get("/api/cart/{user_email}", response_model=list[schemas.CartItemResponse])
def get_cart(user_email: str, db: Session = Depends(get_db)):
    return db.query(models.CartItem).filter(models.CartItem.user_email == user_email).all()


@app.delete("/api/cart/{item_id}")
def remove_from_cart(item_id: int, user_email: str = Query(...), db: Session = Depends(get_db)):
    item = db.query(models.CartItem).filter(
        models.CartItem.id == item_id,
        models.CartItem.user_email == user_email
    ).first()
    if not item:
        raise HTTPException(status_code=404, detail="Cart item not found")
    db.delete(item)
    db.commit()
    return {"message": "Removed"}


@app.delete("/api/cart/user/{user_email}/product/{product_id}")
def remove_from_cart_by_product(product_id: int, user_email: str, size_name: str = Query(None), db: Session = Depends(get_db)):
    q = db.query(models.CartItem).filter(
        models.CartItem.user_email == user_email,
        models.CartItem.product_id == product_id
    )
    if size_name is not None:
        q = q.filter(models.CartItem.size_name == size_name)
    items = q.all()
    for item in items:
        db.delete(item)
    db.commit()
    return {"message": "Removed", "count": len(items)}


# --- 피팅 이미지 생성 (배경제거) ---

@app.delete("/api/products/{product_id}/prepare-fitting")
def reset_fitting_image(product_id: int, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")
    product.fitting_image_url = None
    db.commit()
    return {"message": "fitting_image_url reset"}

@app.delete("/api/admin/reset-all-fitting-images")
def reset_all_fitting_images(db: Session = Depends(get_db)):
    db.query(models.Product).update({models.Product.fitting_image_url: None})
    db.commit()
    return {"message": "All fitting_image_url reset"}

@app.post("/api/products/{product_id}/prepare-fitting")
async def prepare_fitting_image(product_id: int, db: Session = Depends(get_db)):
    product = db.query(models.Product).filter(models.Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    if product.fitting_image_url:
        return {"fitting_image_url": product.fitting_image_url}

    img_path = product.image_url.lstrip("/")
    if not os.path.exists(img_path):
        raise HTTPException(status_code=404, detail="Product image file not found")

    try:
        from rembg import remove as rembg_remove
        from PIL import Image as PILImage
        import io

        with open(img_path, "rb") as f:
            raw = f.read()
        removed_bytes = await run_in_threadpool(rembg_remove, raw)

        # 투명 여백 제거: alpha 채널 기준 bounding box로 크롭
        pil_img = PILImage.open(io.BytesIO(removed_bytes)).convert("RGBA")
        bbox = pil_img.getbbox()   # (left, upper, right, lower) of non-transparent area
        if bbox:
            pil_img = pil_img.crop(bbox)

        buf = io.BytesIO()
        pil_img.save(buf, format="PNG")
        cropped_bytes = buf.getvalue()

        fname = f"fitting_{uuid.uuid4().hex}.png"
        save_path = os.path.join(FITTING_DIR, fname)
        with open(save_path, "wb") as f:
            f.write(cropped_bytes)

        fitting_url = f"/uploads/fitting_images/{fname}"
        product.fitting_image_url = fitting_url
        db.commit()
        return {"fitting_image_url": fitting_url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Background removal failed: {str(e)}")
